spring:
  jpa:
    database: postgresql
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
security:
  jwt:
    tokenExpirationInHours: ${JWT_EXPIRATION}
    secret: ${JWT_SECRET}